markaspot_vision.settings:
  type: config_object
  label: 'Mark-a-Spot Vision settings'
  mapping:
    multiple_uploads:
      type: boolean
      label: 'Allow multiple file uploads'
    auth_type:
      type: string
      label: 'Authentication Type'
    api_key:
      type: string
      label: 'API Key'
    api_url:
      type: uri
      label: 'AI Service API URL'
    ai_model:
      type: string
      label: 'AI Model'
    system_prompt:
      type: text
      label: 'System Prompt'
    image_prompt:
      type: text
      label: 'Image Processing Prompt'
    temperature:
      type: float
      label: 'AI Temperature'
    top_p:
      type: float
      label: 'Top P'
    max_tokens:
      type: integer
      label: 'Max Tokens'
